// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Tag struct {
	ID        int64     `db:"id" json:"id"`
	Name      string    `db:"name" json:"name"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type Task struct {
	ID           int64         `db:"id" json:"id"`
	ParentTaskID sql.NullInt64 `db:"parent_task_id" json:"parent_task_id"`
	Title        string        `db:"title" json:"title"`
	Description  string        `db:"description" json:"description"`
	Status       string        `db:"status" json:"status"`
	Priority     int64         `db:"priority" json:"priority"`
	DueAt        sql.NullTime  `db:"due_at" json:"due_at"`
	CreatedAt    time.Time     `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time     `db:"updated_at" json:"updated_at"`
}

type TaskHistory struct {
	ID        int64     `db:"id" json:"id"`
	TaskID    int64     `db:"task_id" json:"task_id"`
	EventType string    `db:"event_type" json:"event_type"`
	Details   string    `db:"details" json:"details"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type TaskTag struct {
	TaskID int64 `db:"task_id" json:"task_id"`
	TagID  int64 `db:"tag_id" json:"tag_id"`
}

type View struct {
	ID         int64     `db:"id" json:"id"`
	Name       string    `db:"name" json:"name"`
	FilterJson string    `db:"filter_json" json:"filter_json"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
	UpdatedAt  time.Time `db:"updated_at" json:"updated_at"`
}
