// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AddHistory(ctx context.Context, arg AddHistoryParams) (TaskHistory, error)
	AssignTagToTask(ctx context.Context, arg AssignTagToTaskParams) error
	ClearTagsForTask(ctx context.Context, taskID int64) error
	CreateTag(ctx context.Context, name string) (Tag, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateView(ctx context.Context, arg CreateViewParams) (View, error)
	DeleteTag(ctx context.Context, id int64) error
	DeleteTask(ctx context.Context, id int64) error
	DeleteView(ctx context.Context, id int64) error
	GetTagByName(ctx context.Context, name string) (Tag, error)
	GetTask(ctx context.Context, id int64) (Task, error)
	GetViewByName(ctx context.Context, name string) (View, error)
	ListHistoryByTask(ctx context.Context, taskID int64) ([]TaskHistory, error)
	ListTags(ctx context.Context) ([]Tag, error)
	ListTagsForTask(ctx context.Context, taskID int64) ([]Tag, error)
	ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error)
	ListTasksByTags(ctx context.Context, arg ListTasksByTagsParams) ([]Task, error)
	ListViews(ctx context.Context) ([]View, error)
	RemoveTagFromTask(ctx context.Context, arg RemoveTagFromTaskParams) error
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
	UpdateView(ctx context.Context, arg UpdateViewParams) (View, error)
}

var _ Querier = (*Queries)(nil)
