// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const addHistory = `-- name: AddHistory :one
INSERT INTO task_history (task_id, event_type, details)
VALUES (?, ?, ?)
RETURNING id, task_id, event_type, details, created_at
`

type AddHistoryParams struct {
	TaskID    int64  `db:"task_id" json:"task_id"`
	EventType string `db:"event_type" json:"event_type"`
	Details   string `db:"details" json:"details"`
}

func (q *Queries) AddHistory(ctx context.Context, arg AddHistoryParams) (TaskHistory, error) {
	row := q.db.QueryRowContext(ctx, addHistory, arg.TaskID, arg.EventType, arg.Details)
	var i TaskHistory
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.EventType,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const assignTagToTask = `-- name: AssignTagToTask :exec
INSERT OR IGNORE INTO task_tags (task_id, tag_id)
VALUES (?, ?)
`

type AssignTagToTaskParams struct {
	TaskID int64 `db:"task_id" json:"task_id"`
	TagID  int64 `db:"tag_id" json:"tag_id"`
}

func (q *Queries) AssignTagToTask(ctx context.Context, arg AssignTagToTaskParams) error {
	_, err := q.db.ExecContext(ctx, assignTagToTask, arg.TaskID, arg.TagID)
	return err
}

const clearTagsForTask = `-- name: ClearTagsForTask :exec
DELETE FROM task_tags WHERE task_id = ?
`

func (q *Queries) ClearTagsForTask(ctx context.Context, taskID int64) error {
	_, err := q.db.ExecContext(ctx, clearTagsForTask, taskID)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (name)
VALUES (?)
ON CONFLICT(name) DO UPDATE SET name = excluded.name
RETURNING id, name, created_at
`

func (q *Queries) CreateTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (title, description, status, priority, due_at, parent_task_id)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, parent_task_id, title, description, status, priority, due_at, created_at, updated_at
`

type CreateTaskParams struct {
	Title        string        `db:"title" json:"title"`
	Description  string        `db:"description" json:"description"`
	Status       string        `db:"status" json:"status"`
	Priority     int64         `db:"priority" json:"priority"`
	DueAt        sql.NullTime  `db:"due_at" json:"due_at"`
	ParentTaskID sql.NullInt64 `db:"parent_task_id" json:"parent_task_id"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.DueAt,
		arg.ParentTaskID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ParentTaskID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createView = `-- name: CreateView :one
INSERT INTO views (name, filter_json)
VALUES (?, ?)
RETURNING id, name, filter_json, created_at, updated_at
`

type CreateViewParams struct {
	Name       string `db:"name" json:"name"`
	FilterJson string `db:"filter_json" json:"filter_json"`
}

func (q *Queries) CreateView(ctx context.Context, arg CreateViewParams) (View, error) {
	row := q.db.QueryRowContext(ctx, createView, arg.Name, arg.FilterJson)
	var i View
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FilterJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = ?
`

func (q *Queries) DeleteTag(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTag, id)
	return err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = ?
`

func (q *Queries) DeleteTask(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const deleteView = `-- name: DeleteView :exec
DELETE FROM views WHERE id = ?
`

func (q *Queries) DeleteView(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteView, id)
	return err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name, created_at FROM tags WHERE name = ?
`

func (q *Queries) GetTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByName, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, parent_task_id, title, description, status, priority, due_at, created_at, updated_at
FROM tasks
WHERE id = ?
`

func (q *Queries) GetTask(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ParentTaskID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getViewByName = `-- name: GetViewByName :one
SELECT id, name, filter_json, created_at, updated_at
FROM views
WHERE name = ?
`

func (q *Queries) GetViewByName(ctx context.Context, name string) (View, error) {
	row := q.db.QueryRowContext(ctx, getViewByName, name)
	var i View
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FilterJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listHistoryByTask = `-- name: ListHistoryByTask :many
SELECT id, task_id, event_type, details, created_at
FROM task_history
WHERE task_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListHistoryByTask(ctx context.Context, taskID int64) ([]TaskHistory, error) {
	rows, err := q.db.QueryContext(ctx, listHistoryByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskHistory
	for rows.Next() {
		var i TaskHistory
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.EventType,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, name, created_at FROM tags ORDER BY name ASC
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForTask = `-- name: ListTagsForTask :many
SELECT tags.id, tags.name, tags.created_at
FROM tags
JOIN task_tags ON task_tags.tag_id = tags.id
WHERE task_tags.task_id = ?
ORDER BY tags.name ASC
`

func (q *Queries) ListTagsForTask(ctx context.Context, taskID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTagsForTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, parent_task_id, title, description, status, priority, due_at, created_at, updated_at
FROM tasks
WHERE (?1 = '' OR title LIKE '%' || ?1 || '%' OR description LIKE '%' || ?1 || '%')
  AND (?2 = '' OR status = ?2)
  AND (?3 IS NULL OR due_at <= ?3)
  AND (?4 IS NULL OR due_at >= ?4)
ORDER BY created_at DESC
`

type ListTasksParams struct {
	Query     interface{} `db:"query" json:"query"`
	Status    interface{} `db:"status" json:"status"`
	DueBefore interface{} `db:"due_before" json:"due_before"`
	DueAfter  interface{} `db:"due_after" json:"due_after"`
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks,
		arg.Query,
		arg.Status,
		arg.DueBefore,
		arg.DueAfter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ParentTaskID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.DueAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByTags = `-- name: ListTasksByTags :many
SELECT DISTINCT tasks.id, tasks.parent_task_id, tasks.title, tasks.description, tasks.status, tasks.priority, tasks.due_at, tasks.created_at, tasks.updated_at
FROM tasks
JOIN task_tags ON task_tags.task_id = tasks.id
JOIN tags ON tags.id = task_tags.tag_id
WHERE tags.name IN (/*SLICE:tags*/?)
  AND (?2 = '' OR tasks.title LIKE '%' || ?2 || '%' OR tasks.description LIKE '%' || ?2 || '%')
ORDER BY tasks.created_at DESC
`

type ListTasksByTagsParams struct {
	Tags  []string    `db:"tags" json:"tags"`
	Query interface{} `db:"query" json:"query"`
}

func (q *Queries) ListTasksByTags(ctx context.Context, arg ListTasksByTagsParams) ([]Task, error) {
	query := listTasksByTags
	var queryParams []interface{}
	if len(arg.Tags) > 0 {
		for _, v := range arg.Tags {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:tags*/?", strings.Repeat(",?", len(arg.Tags))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:tags*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Query)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ParentTaskID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.DueAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listViews = `-- name: ListViews :many
SELECT id, name, filter_json, created_at, updated_at
FROM views
ORDER BY name ASC
`

func (q *Queries) ListViews(ctx context.Context) ([]View, error) {
	rows, err := q.db.QueryContext(ctx, listViews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []View
	for rows.Next() {
		var i View
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FilterJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagFromTask = `-- name: RemoveTagFromTask :exec
DELETE FROM task_tags WHERE task_id = ? AND tag_id = ?
`

type RemoveTagFromTaskParams struct {
	TaskID int64 `db:"task_id" json:"task_id"`
	TagID  int64 `db:"tag_id" json:"tag_id"`
}

func (q *Queries) RemoveTagFromTask(ctx context.Context, arg RemoveTagFromTaskParams) error {
	_, err := q.db.ExecContext(ctx, removeTagFromTask, arg.TaskID, arg.TagID)
	return err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title = ?,
    description = ?,
    status = ?,
    priority = ?,
    due_at = ?,
    parent_task_id = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, parent_task_id, title, description, status, priority, due_at, created_at, updated_at
`

type UpdateTaskParams struct {
	Title        string        `db:"title" json:"title"`
	Description  string        `db:"description" json:"description"`
	Status       string        `db:"status" json:"status"`
	Priority     int64         `db:"priority" json:"priority"`
	DueAt        sql.NullTime  `db:"due_at" json:"due_at"`
	ParentTaskID sql.NullInt64 `db:"parent_task_id" json:"parent_task_id"`
	ID           int64         `db:"id" json:"id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.DueAt,
		arg.ParentTaskID,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ParentTaskID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateView = `-- name: UpdateView :one
UPDATE views
SET name = ?,
    filter_json = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, filter_json, created_at, updated_at
`

type UpdateViewParams struct {
	Name       string `db:"name" json:"name"`
	FilterJson string `db:"filter_json" json:"filter_json"`
	ID         int64  `db:"id" json:"id"`
}

func (q *Queries) UpdateView(ctx context.Context, arg UpdateViewParams) (View, error) {
	row := q.db.QueryRowContext(ctx, updateView, arg.Name, arg.FilterJson, arg.ID)
	var i View
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FilterJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
